### ISSUE TITLE
[Clone] 스포티파이 로그인 화면 UI 구현

### ISSUE THREAD

**Issue by deslog** [deslog/SwiftUIDev#1]
## 📝 Todo
케미가 갑자기 준 숙제, 스포티파이 로그인 화면을 구현합니다.

<img width="303" alt="image" src="https://user-images.githubusercontent.com/96969693/183260541-7b7be43f-ae45-4f34-bb68-8d2ca36a5103.png">

## 📝 ETC
12일까지~ 심심하면 하자

**Comment by deslog** [comment]
### 현재 여기까지 완료 - 남은작업
 - [x] 패딩값 수정 (상수로 지정되어있는거 다 빼서 수정)
 - [x] sign up 에 있는 google 이미지 없애기
 - [x] 기기별로 화면 무너지지 않는지 확인하기
 - [x] 코드 정리 및 리팩토링

<img src="https://user-images.githubusercontent.com/96969693/183265130-ee68e2fb-3e40-4989-aa3c-bc912c0e87ef.png"  width="300"/>

**Comment by deslog** [comment]
뭐야 제목 글씨체가 조금 다른듯? 뭐지이이

**Comment by MMMIIIN** [comment]
고맙습니다 ^________^
브라운 짱 👍
